#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_seed.py — สร้าง db/seed.sql จากไฟล์ Excel Feasibility (Rev 2.4.7)
ใช้เมื่อมี Excel rev ใหม่:  python3 generate_seed.py "<path to xlsx>" > seed.sql
- sheet "Item"        → ตาราง item (ทั้งหมด รวม Blocked)
- sheet "0) Reference"→ ตาราง fx_rate (รอบประกาศฝ่ายการเงิน)
- master ชุดเล็ก (service_type, sale_team, overhead, ฯลฯ) คงที่ในสคริปต์นี้
  (ตรวจทานกับ Reference sheet + serviceData ในแอปแล้ว — sheet โครงสร้างไม่เอื้อต่อการ parse ตรง)
"""
import sys, warnings
warnings.filterwarnings('ignore')
import openpyxl

XLSX = sys.argv[1] if len(sys.argv) > 1 else '/sessions/zealous-fervent-turing/mnt/uploads/(Rev.2.4.7) Feasibility 1toAll (Draft).xlsx'

def q(s):
    if s is None: return 'null'
    return "'" + str(s).replace("'", "''").replace('\\', '\\\\').replace('\n', ' ').strip() + "'"

def num(v):
    if v in (None, ''): return 'null'
    try: return str(round(float(v), 2))
    except Exception: return 'null'

def boo(v):
    s = str(v).strip().lower()
    if s == 'true': return 'true'
    if s == 'false': return 'false'
    return 'null'

def dat(v):
    if v in (None, ''): return 'null'
    s = str(v)[:10]
    return q(s) if len(s) == 10 and s[4] == '-' else 'null'

def parse_vendor(desc):
    # prefix "VENDOR - rest" → vendor (ข้าม [Blocked - ...] notes)
    if desc.startswith('['): return None
    if ' - ' in desc:
        v = desc.split(' - ', 1)[0].strip()
        if 1 < len(v) <= 40: return v
    return None

wb = openpyxl.load_workbook(XLSX, read_only=True, data_only=True)
out = []
out.append('-- seed.sql — generated by generate_seed.py จาก ' + XLSX.split('/')[-1])
out.append('begin;')
out.append('truncate table item, fx_rate, service_type, sale_team, overhead_type, other_expense_type, project_type, payment_type, install_pmcm_standard, mrc_catalog, staff restart identity cascade;')

# ---------------- item ----------------
ws = wb['Item']
rows, seen, dups = [], set(), 0
for r in ws.iter_rows(min_row=4, values_only=True):
    no = r[1]
    if not no: continue
    no = str(no).strip()
    if no in seen: dups += 1; continue
    seen.add(no)
    desc = str(r[0] or '').strip() or no
    rows.append('(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)' % (
        q(no), q(desc), q(parse_vendor(desc)) if parse_vendor(desc) else 'null',
        q(str(r[2] or 'PCS').strip()), num(r[3]) if num(r[3]) != 'null' else '0',
        num(r[4]), num(r[7]), dat(r[5]), dat(r[6]),
        boo(r[8]), boo(r[9]),
        boo(r[10]) if boo(r[10]) != 'null' else 'false',
        boo(r[11]) if boo(r[11]) != 'null' else 'false'))
cols = '(item_no,description,vendor_name,base_uom,unit_price,unit_price_ex_vat_old,promo_price,promo_start,promo_end,allow_line_disc,allow_invoice_disc,price_includes_vat,blocked)'
for i in range(0, len(rows), 500):
    out.append('insert into item ' + cols + ' values\n' + ',\n'.join(rows[i:i+500]) + ';')
sys.stderr.write('item rows: %d (dups skipped: %d)\n' % (len(rows), dups))

# ---------------- fx_rate (Reference R38+) ----------------
ref = wb['0) Reference']
fx = []
grid = list(ref.iter_rows(min_row=1, max_row=83, values_only=True))
start_row = None
for i, r in enumerate(grid):
    if r[2] is not None and str(r[2]).strip() == 'Start': start_row = i + 1; break
if start_row:
    for r in grid[start_row:]:
        s, e, usd, cny = r[2], r[3], r[4], r[5]
        if s is None or usd is None: break
        fx.append('(%s,%s,%s,%s)' % (dat(s), dat(e), num(usd), num(cny)))
if fx:
    out.append('insert into fx_rate (start_date,end_date,usd,cny) values\n' + ',\n'.join(fx) + ';')
sys.stderr.write('fx_rate rows: %d\n' % len(fx))

# ---------------- service_type (ตรวจทานกับ Reference R6-R22) ----------------
ST = [
 ('Communication | MA','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Communication | Voice','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Communication | PABX','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Communication | UC','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Communication | Zoom Phone','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Communication | Zoom CC','Communication','Solution Architect Manager','Woraphat Laohaudomphan',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Audio Visual (A/V)','Audio Visual','Head of AV (Acting)','Dumrongrit Pantaraksakul',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Zound & Workplace','Audio Visual','Acoustic Engineer','Komen Srithaneschai',0.03,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Zoom','Audio Visual','Head of Pre-Sales','Noppadol Sanmaneechai',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Data & Security | Cloud Services','Data & Security','Data & Security Manager','Somjet',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Data & Security | Cyber Security','Data & Security','Data & Security Manager','Vichaphas Boonraksa',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('Data & Security | Networking','Data & Security','Data & Security Manager','Vichaphas Boonraksa',0.01,0.30,0.20,'AV/Zoom/Voice/Zound'),
 ('SI Audio Visual','System Integration','Project Engineer','Peerapan Sartprapun',0.01,0.15,0.10,'SI/Internet/Cloud'),
 ('SI Government','System Integration','Head of Pre-Sales','Noppadol Sanmaneechai',0.01,0.15,0.10,'SI/Internet/Cloud'),
 ('SI Connectivity (AM)','System Integration','Head of Pre-Sales','Noppadol Sanmaneechai',0.01,1.00,0.10,'SI/Internet/Cloud'),
 ('SI Government (AM1)','System Integration','Head of Pre-Sales','Noppadol Sanmaneechai',0.01,0.15,0.10,'SI/Internet/Cloud'),
 ('SI Government (AM2)','System Integration','Head of Pre-Sales','Noppadol Sanmaneechai',0.01,0.15,0.10,'SI/Internet/Cloud'),
]
out.append('insert into service_type (code,category,head_role,head_name,mkt_rate,appv_l1,appv_l2,approval_group,sort) values\n' +
  ',\n'.join('(%s,%s,%s,%s,%s,%s,%s,%s,%d)' % (q(a),q(b),q(c),q(d),e,f,g,q(h),i+1) for i,(a,b,c,d,e,f,g,h) in enumerate(ST)) + ';')

# ---------------- sale_team ----------------
TEAMS = [
 ('Inside & Online','Kritpas Vorathananon','CPO','Montree Montreemanee'),
 ('Account Management 1','Pasu Markboonsog','COO','Parinya Sahabhatsombut'),
 ('Account Management 2','Piyanant Anukul','COO','Parinya Sahabhatsombut'),
 ('Government','Weerachai Nilnampetch','CPO','Montree Montreemanee'),
 ('Data & Security','Jirad Kachanunyanawut','CPO','Montree Montreemanee'),
 ('Partner : Audio Visual (A/V)','-','CPO','Montree Montreemanee'),
 ('Zound & Workplace','Visanu Chintanasirikul','CPO','Montree Montreemanee'),
 ('Center','-','COS','Ponpimol Nonsopa'),
]
out.append('insert into sale_team (name,head_name,c_level_role,c_level_name,sort) values\n' +
  ',\n'.join('(%s,%s,%s,%s,%d)' % (q(a),q(b),q(c),q(d),i+1) for i,(a,b,c,d) in enumerate(TEAMS)) + ';')

# ---------------- overhead_type ----------------
OH = [('ซื้อมาขายไป (3%)',0.03,False),('โครงการปกติ (5%)',0.05,True),('โครงการใหญ่ (7%)',0.07,False),
      ('โครงการพิเศษ (9%)',0.09,False),('บริการ Zoom (5%)',0.05,False),('บริการ Internet (5%)',0.05,False),
      ('บริการ Cloud Service (5%)',0.05,False),('โครงการซับซ้อน (15%)',0.15,False)]
out.append('insert into overhead_type (label,pct,is_default,sort) values\n' +
  ',\n'.join('(%s,%s,%s,%d)' % (q(a),b,'true' if c else 'false',i+1) for i,(a,b,c) in enumerate(OH)) + ';')

# ---------------- other_expense_type ----------------
OTHER = ['ค่าประสานงานโครงการ','ค่าติดตั้งเพิ่มเติม','ค่าอบรม Training','ค่าดูแลระบบ IT Outsourcing','ค่าเลี้ยงรับรองต่างๆ']
out.append('insert into other_expense_type (name,sort) values\n' +
  ',\n'.join('(%s,%d)' % (q(a),i+1) for i,a in enumerate(OTHER)) + ';')

# ---------------- project_type / payment_type ----------------
out.append('insert into project_type (name,sort) values\n' +
  ',\n'.join("(%s,%d)" % (q(a),i+1) for i,a in enumerate(['New','Move','Add','Change','Decrease','Renew','Transfer'])) + ';')
out.append('insert into payment_type (name,sort) values\n' +
  ',\n'.join("(%s,%d)" % (q(a),i+1) for i,a in enumerate(['Lumpsum','Buffet','Minimum','Per Minute','Capped','One Time','Rental'])) + ';')

# ---------------- install_pmcm_standard (sheet 1) Install / 2) PMCM) ----------------
STD = [('STD-01','Professional Service','PM Service / Design / Config / Service',2000),
 ('STD-02','Car','Transportation',500),('STD-03','Flight (Back-Forth)','Transportation',0),
 ('STD-04','Hotel','Accommodation',2000),('STD-05','Manday/perday','Manager Manday',2000),
 ('STD-06','Manday/perday Project Co (AE)','Project CO Manday',1000),('STD-07','Manday/perday PM','PM Manday',2500),
 ('STD-08','Manday/perday ENG','Engineering Manday',1500),
 ('STD-09','Installation & Configuration: Desk Phone/ATA','VoIP Configuration',20),
 ('STD-10','Training Manday','Installation & Training',10000),('STD-11','Numbering Installation','Numbering Installation',1000),
 ('STD-12','Car & Installation & Configuration','Transportation',2000),
 ('STD-13','Installation SBC / E1 / ATA','Installation SBC / E1 / ATA',30000),
 ('STD-14','Others','ปรับประมาณการณ์ตามเหมาะสม',0)]
out.append('insert into install_pmcm_standard (code,name,meta,unit_price,sort) values\n' +
  ',\n'.join('(%s,%s,%s,%s,%d)' % (q(a),q(b),q(c),d,i+1) for i,(a,b,c,d) in enumerate(STD)) + ';')

# ---------------- mrc_catalog (ที่มา: แอป) ----------------
MRC = [('MRC-AIS-1G','AIS Business','Internet leased line 1 Gbps (Primary · 99.5% SLA)',28000,42000),
 ('MRC-AIS-500M','AIS Business','Internet leased line 500 Mbps',18000,27000),
 ('MRC-NT-1G','NT (TOT)','Internet leased line 1 Gbps',25000,38000),
 ('MRC-TRUE-1G','True Business','Internet leased line 1 Gbps',26000,39000),
 ('MRC-TRUE-5G','True Business','5G backup link 200 Mbps (Failover)',2800,3800),
 ('MRC-AIS-5G','AIS Business','5G SIM backup link 100 Mbps',1800,2500),
 ('MRC-DTAC-5G','DTAC Business','5G SIM enterprise data plan',2200,3200),
 ('MRC-MS365-E3','Microsoft','Microsoft 365 E3 per user/mo',1200,1650),
 ('MRC-MS365-BP','Microsoft','Microsoft 365 Business Premium per user/mo',850,1200),
 ('MRC-AZURE','Microsoft','Azure cloud compute (estimated)',15000,22000),
 ('MRC-GOOG-WS','Google','Google Workspace Business Plus per user/mo',700,980),
 ('MRC-ZOOM-PRO','Zoom','Zoom Pro license per user/mo',500,750),
 ('MRC-ZOOM-BIZ','Zoom','Zoom Business per user/mo',800,1200),
 ('MRC-ZOOM-PHONE','Zoom','Zoom Phone license per user/mo',600,900),
 ('MRC-NOC-247','Internal','24x7 NOC monitoring service',18000,24800),
 ('MRC-SOC','Internal','SOC managed security service/mo',35000,50000),
 ('MRC-FW-MA','Fortinet','FortiGate MA support per device/mo',2500,3800),
 ('MRC-CCTV-MA','Internal','CCTV system maintenance/mo',8000,12000),
 ('MRC-MAXHUB-MA','MAXHUB','IFP maintenance contract per unit/mo',800,1200),
 ('MRC-LED-MA','Leyard','LED wall maintenance/mo',12000,18000)]
out.append('insert into mrc_catalog (code,vendor,description,default_cost,default_sale) values\n' +
  ',\n'.join('(%s,%s,%s,%d,%d)' % (q(a),q(b),q(c),d,e) for a,b,c,d,e in MRC) + ';')

# ---------------- staff ----------------
SALES = [('Chananthicha Wongsan','คุณแอ๊ว','Account Management 1'),('Parinya Sahabhatsombut','คุณเม้ง','Account Management 1'),
 ('Pimpilai Puanglamyai','คุณพิม','Account Management 1'),('Phongthorn Meesaeng','คุณป้อง','Account Management 1'),
 ('Punika Angkanont','คุณแจง','Account Management 1'),('Saokaew Singholsai','คุณเสาร์แก้ว','Account Management 1')]
PRESALES = [('Noppadol Sanmaneechai',None),('Chaiyawat Sukmanee','คุณวิน'),('Nitinat Chumcumsin','คุณแป๊บ'),
 ('Komen Srithaneschai','คุณหนึ่ง'),('Thanakorn Thapprasert','เอก'),('Wantawat Jitsilp','Tong/ต้อง')]
vals = ['(%s,%s,%s,%s,%d)' % (q(a),q(b),q('sale'),q(t),i+1) for i,(a,b,t) in enumerate(SALES)]
vals += ['(%s,%s,%s,null,%d)' % (q(a),q(b) if b else 'null',q('presale'),i+1) for i,(a,b) in enumerate(PRESALES)]
out.append('insert into staff (full_name,nickname,role,sale_team,sort) values\n' + ',\n'.join(vals) + ';')

out.append('commit;')
print('\n'.join(out))
